---
 - name: start services
   hosts: localhost

   vars:
       DOCKER_USERNAME: myroslavlevchyk
       DOCKER_PASSWORD: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61346330623164323330313236313864666630323432383434636530633334633930333338356336
          3838393232343436373965633763323935313130633730660a306434393630386665366539363734
          31663936653365653637633937613162313139353866323539313832393238303464396563636463
          6365636439303363350a356162326661626439376333326566333136626635346135633336306634
          3036
       BUILD_NUMBER: {{ lookup('env','BUILD_NUMBER') }}   
  #  tasks:
  #  - name: Clone a github repository
  #    git:
  #      repo: https://github.com/myroslavlevchyk/4pet.git
  #      dest: /home/myroslav/final_task/final_pet/
  #      clone: yes
  #      update: yes

   tasks:
     - name: Delete content & directory
       file:
         state: absent
         path: /home/myroslav/final_task/final_pet/
    #  - name: Clear dir
    #    command: rm -rf /home/myroslav/final_task/final_pet/

     - name: Clone Git Repo
#       git:
       ansible.builtin.git:
         repo: https://github.com/myroslavlevchyk/4pet.git
         dest: /home/myroslav/final_task/final_pet
        #  force: yes
        #  clone: yes
        #  update: yes
        #  mode: 0755
         single_branch: yes
         version: feature

     - name: Hadolint
       command: hadolint /home/myroslav/final_task/final/Dockerfile

     - name: MVNW Package
       command: chdir=/home/myroslav/final_task/final_pet ./mvnw package  
    
#     - name: Build_number
     - debug: msg="{{ lookup('env','BUILD_NUMBER') }}"           

     - name: Build Docker container image
       command: chdir=/home/myroslav/final_task/final_pet docker build -t myroslavlevchyk/petclinic:latest -f /home/myroslav/final_task/final/Dockerfile .        

     - name: Tag Docker container image
       command: chdir=/home/myroslav/final_task/final_pet docker build -t myroslavlevchyk/petclinic:"{{ BUILD_NUMBER }}" -f /home/myroslav/final_task/final/Dockerfile .        

    #  - name: ECHO Docker container image
    #    command: docker login -u={{DOCKER_USERNAME}} -p={{DOCKER_PASSWORD}}
     - name: Log into DockerHub
       community.docker.docker_login:
         username: "{{ DOCKER_USERNAME }}"
         password: "{{ DOCKER_PASSWORD }}"

     - name: PUSH Docker container image
       command: docker push myroslavlevchyk/petclinic:latest

